name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Publish
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'libcuda.so' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env production --minify src/index.js
          environment: production
          
