name: Deploy to Cloudflare Workers(Staging)

on:
  pull_request_target:
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Publish
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'libcuda.so' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env staging --minify src/index.js
          environment: staging
